## EU DATA cleaning

## Remove blank Names

In [3]:
import pandas as pd
import re

### Load Data

In [44]:
df = pd.read_csv("name-fix-eu-list.csv")

In [45]:
df.columns

Index(['Entity_LogicalId', 'Entity_EU_ReferenceNumber', 'Entity_Remark',
       'Entity_SubjectType', 'Entity_SubjectType_ClassificationCode',
       'NameAlias_LastName', 'NameAlias_FirstName', 'NameAlias_MiddleName',
       'NameAlias_WholeName', 'NameAlias_Title', 'NameAlias_Function',
       'NameAlias_LogicalId', 'NameAlias_Remark', 'Address_City',
       'Address_Street', 'Address_PoBox', 'Address_ZipCode', 'Address_Region',
       'Address_Place', 'Address_ContactInfo', 'Address_Remark',
       'BirthDate_BirthDate', 'BirthDate_Day', 'BirthDate_Month',
       'BirthDate_Year', 'BirthDate_Place', 'BirthDate_City',
       'BirthDate_Remark', 'Identification_Number', 'Identification_Remark',
       'Citizenship_Remark'],
      dtype='object')

In [46]:
alias_cols = [
    "NameAlias_LastName",
    "NameAlias_FirstName",
    "NameAlias_MiddleName",
    "NameAlias_WholeName",
    "NameAlias_Title",
    "NameAlias_Function",
    "NameAlias_LogicalId",
    "NameAlias_Remark"
]

In [47]:
# Keep only rows where at least one alias column has English text
df = df[df[alias_cols].apply(lambda row: any(has_english(val) for val in row), axis=1)]

In [48]:
# Drop columns that are completely empty or contain only NaN/empty/whitespace
df = df.dropna(axis=1, how="all")  # Drop fully empty columns
df = df[[col for col in df.columns if df[col].apply(lambda x: str(x).strip() if pd.notna(x) else "").any()]]  # Remove whitespace-only columns

In [49]:
df.to_csv("output_namealias_english_2.csv", index=False)

### Load Data

## Remove blank Address

In [58]:
df = pd.read_csv("eu-list-IDN-src.csv")

In [59]:
df.columns

Index(['Entity_LogicalId', 'Entity_EU_ReferenceNumber', 'Entity_SubjectType',
       'Entity_SubjectType_ClassificationCode', 'Identification_Number',
       'Identification_TypeCode', 'Identification_TypeDescription',
       'Identification_Region', 'Identification_CountryIso2Code',
       'Identification_CountryDescription', 'Identification_Remark'],
      dtype='object')

In [60]:
# Alias-related columns
alias_cols = [
'Identification_Number',
       'Identification_TypeCode', 'Identification_TypeDescription',
       'Identification_Region', 'Identification_CountryIso2Code',
       'Identification_CountryDescription', 'Identification_Remark'
]

In [61]:
# Function to check if a value has English letters
def has_english(text):
    if pd.isna(text):
        return False
    return bool(re.search(r"[A-Za-z]", str(text)))

In [62]:
# Keep only rows where at least one alias column has English text
df = df[df[alias_cols].apply(lambda row: any(has_english(val) for val in row), axis=1)]

In [63]:
# Drop columns that are completely empty or contain only NaN/empty/whitespace
df = df.dropna(axis=1, how="all")  # Drop fully empty columns
df = df[[col for col in df.columns if df[col].apply(lambda x: str(x).strip() if pd.notna(x) else "").any()]]  # Remove whitespace-only columns

In [64]:
df.to_csv("output_IDN_english.csv", index=False)

### Remove Blank BirthDate

In [70]:
df = pd.read_csv("eu-list-BirthDate-src.csv")

In [71]:
df.columns

Index(['Entity_LogicalId', 'Entity_EU_ReferenceNumber', 'BirthDate_BirthDate',
       'BirthDate_Day', 'BirthDate_Month', 'BirthDate_Year',
       'BirthDate_Region', 'BirthDate_Place', 'BirthDate_City',
       'BirthDate_CountryIso2Code', 'BirthDate_CountryDescription',
       'BirthDate_Remark'],
      dtype='object')

In [72]:
# Alias-related columns
alias_cols = [
'BirthDate_BirthDate',
       'BirthDate_Day', 'BirthDate_Month', 'BirthDate_Year',
       'BirthDate_Region', 'BirthDate_Place', 'BirthDate_City',
       'BirthDate_CountryIso2Code', 'BirthDate_CountryDescription',
       'BirthDate_Remark'
]

In [73]:
# Function to check if a value has English letters
def has_english(text):
    if pd.isna(text):
        return False
    return bool(re.search(r"[A-Za-z]", str(text)))

In [74]:
# Keep only rows where at least one alias column has English text
df = df[df[alias_cols].apply(lambda row: any(has_english(val) for val in row), axis=1)]

In [75]:
# Drop columns that are completely empty or contain only NaN/empty/whitespace
df = df.dropna(axis=1, how="all")  # Drop fully empty columns
df = df[[col for col in df.columns if df[col].apply(lambda x: str(x).strip() if pd.notna(x) else "").any()]]  # Remove whitespace-only columns

In [76]:
df.to_csv("output_BirthDt_english.csv", index=False)

### Remove Blank Citizen

In [77]:
df = pd.read_csv("eu-list-Citizen-src.csv")

In [78]:
df.columns

Index(['Entity_LogicalId', 'Entity_EU_ReferenceNumber', 'Entity_SubjectType',
       'Entity_SubjectType_ClassificationCode', 'Citizenship_CountryIso2Code',
       'Citizenship_Remark'],
      dtype='object')

In [79]:
# Alias-related columns
alias_cols = [
'Citizenship_CountryIso2Code',
       'Citizenship_Remark'
]

In [84]:
# Function to check if a value has English letters
def has_english(text):
    if pd.isna(text):
        return False
    return bool(re.search(r"[A-Za-z]", str(text)))

In [81]:
# Keep only rows where at least one alias column has English text
df = df[df[alias_cols].apply(lambda row: any(has_english(val) for val in row), axis=1)]

In [82]:
# Drop columns that are completely empty or contain only NaN/empty/whitespace
df = df.dropna(axis=1, how="all")  # Drop fully empty columns
df = df[[col for col in df.columns if df[col].apply(lambda x: str(x).strip() if pd.notna(x) else "").any()]]  # Remove whitespace-only columns

In [83]:
df.to_csv("output_Citizen_english.csv", index=False)

# Final Data

In [4]:
structure = ['ID', 'Name', 'Type', 'Title', 'Designation', 'DOB', 'POB', 'Nationality', 'PassportNum', 'IssueDate', 'NID', 'Address', 'Listed', 'Other']

In [5]:
df_name = pd.read_csv("output_namealias_english_2.csv")

In [6]:
df_name.head(3)

,Entity_LogicalId,Entity_EU_ReferenceNumber,Entity_Remark,Entity_SubjectType,Entity_SubjectType_ClassificationCode,NameAlias_LastName,NameAlias_FirstName,NameAlias_MiddleName,NameAlias_WholeName,NameAlias_Title,NameAlias_Function,NameAlias_LogicalId,NameAlias_Remark
0,13,EU.27.28,(UNSC RESOLUTION 1483),P,person,Hussein Al-Tikriti,Saddam,NaN,Saddam Hussein Al-Tikriti,NaN,NaN,17.0,NaN
1,13,EU.27.28,(UNSC RESOLUTION 1483),P,person,NaN,NaN,NaN,Abu Ali,NaN,NaN,19.0,NaN
2,13,EU.27.28,(UNSC RESOLUTION 1483),P,person,NaN,NaN,NaN,Abou Ali,NaN,NaN,380.0,NaN

In [7]:
df_address = pd.read_csv("output_Address_english.csv")

In [8]:
df_address.head(3)

,Entity_LogicalId,Entity_EU_ReferenceNumber,Address_City,Address_Street,Address_PoBox,Address_ZipCode,Address_Region,Address_Place,Address_AsAtListingTime,Address_ContactInfo,Address_CountryIso2Code,Address_CountryDescription,Address_Remark
0,327,EU.266.94,Peshawar,office locations: Headquarters — G. T. Road (p...,NaN,NaN,NaN,NaN,NO,NaN,PK,PAKISTAN,NaN
1,327,EU.266.94,Jalabad,"Cheprahar Hadda, Mia Omar Sabaqah School",NaN,NaN,NaN,NaN,NO,NaN,AF,AFGHANISTAN,NaN
2,330,EU.522.39,Lahore,"Jamia Masjid Sulaiman Park, Begum Pura",NaN,NaN,NaN,NaN,NO,PHONE[042-681 20 81],PK,PAKISTAN,NaN

In [9]:
df_BirthDt = pd.read_csv("output_BirthDt_english.csv")

In [10]:
df_BirthDt.head(3)

,Entity_LogicalId,Entity_EU_ReferenceNumber,BirthDate_BirthDate,BirthDate_Day,BirthDate_Month,BirthDate_Year,BirthDate_Region,BirthDate_Place,BirthDate_City,BirthDate_CountryIso2Code,BirthDate_CountryDescription,BirthDate_Remark
0,13,EU.27.28,1937-04-28,28.0,4.0,1937.0,NaN,NaN,"al-Awja, near Tikrit",IQ,IRAQ,NaN
1,20,EU.39.56,NaN,NaN,NaN,1965.0,NaN,NaN,Baghdad,00,UNKNOWN,NaN
2,20,EU.39.56,NaN,NaN,NaN,1966.0,NaN,NaN,Baghdad,00,UNKNOWN,NaN

In [11]:
df_Citizen = pd.read_csv("output_Citizen_english.csv")

In [12]:
df_Citizen.head(3)

,Entity_LogicalId,Entity_EU_ReferenceNumber,Entity_SubjectType,Entity_SubjectType_ClassificationCode,Citizenship_CountryIso2Code,Citizenship_Remark
0,13,EU.27.28,P,person,IQ,NaN
1,20,EU.39.56,P,person,IQ,NaN
2,23,EU.16.62,P,person,IQ,NaN

In [13]:
df_IDN = pd.read_csv("output_IDN_english.csv")

In [14]:
df_IDN.head(3)

,Entity_LogicalId,Entity_EU_ReferenceNumber,Entity_SubjectType,Entity_SubjectType_ClassificationCode,Identification_Number,Identification_TypeCode,Identification_TypeDescription,Identification_Region,Identification_CountryIso2Code,Identification_Remark
0,83,EU.77.33,P,person,34409/129 (other-Other identification number) ...,other,Other identification number,NaN,00,july 1997
1,191,EU.3579.2,P,person,488555 (passport-National passport),passport,National passport,NaN,00,NaN
2,505,EU.471.56,P,person,D 0001203 (passport-National passport) ((afgha...,passport,National passport,NaN,AF,(afghan passport)

In [15]:
# Example: aggregate helper
def aggregate_df(df, key_col, prefix):
    # group by Entity_LogicalId, collect all other cols into lists
    return df.groupby(key_col).agg(lambda x: list(x.dropna().unique())).add_prefix(prefix + "_")

In [16]:
#df_name_agg = aggregate_df(df_name, "Entity_LogicalId", "NameAlias")
df_address_agg = aggregate_df(df_address, "Entity_LogicalId", "Address")
df_birth_agg = aggregate_df(df_BirthDt, "Entity_LogicalId", "Birth")
df_citizen_agg = aggregate_df(df_Citizen, "Entity_LogicalId", "Citizen")
df_idn_agg = aggregate_df(df_IDN, "Entity_LogicalId", "IDN")

In [17]:
# Merge them all together on Entity_LogicalId
final_df = (
    df_name
    .merge(df_address_agg, on="Entity_LogicalId", how="left")
    # .merge(df_birth_agg, on="Entity_LogicalId", how="left")
    .merge(df_citizen_agg, on="Entity_LogicalId", how="left")
    .merge(df_idn_agg, on="Entity_LogicalId", how="left")
)

In [19]:
# Use NameAlias_WholeName as ID
final_df

,Entity_LogicalId,Entity_EU_ReferenceNumber,Entity_Remark,Entity_SubjectType,Entity_SubjectType_ClassificationCode,NameAlias_LastName,NameAlias_FirstName,NameAlias_MiddleName,NameAlias_WholeName,NameAlias_Title,...,Citizen_Citizenship_Remark,IDN_Entity_EU_ReferenceNumber,IDN_Entity_SubjectType,IDN_Entity_SubjectType_ClassificationCode,IDN_Identification_Number,IDN_Identification_TypeCode,IDN_Identification_TypeDescription,IDN_Identification_Region,IDN_Identification_CountryIso2Code,IDN_Identification_Remark
0,13,EU.27.28,(UNSC RESOLUTION 1483),P,person,Hussein Al-Tikriti,Saddam,NaN,Saddam Hussein Al-Tikriti,NaN,...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,13,EU.27.28,(UNSC RESOLUTION 1483),P,person,NaN,NaN,NaN,Abu Ali,NaN,...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,13,EU.27.28,(UNSC RESOLUTION 1483),P,person,NaN,NaN,NaN,Abou Ali,NaN,...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20,EU.39.56,(Saddam's second son),P,person,Hussein Al-Tikriti,Qusay,Saddam,Qusay Saddam Hussein Al-Tikriti,NaN,...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20,EU.39.56,(Saddam's second son),P,person,Hussein Al-Tikriti,Qoussaï,Saddam,Qoussaï Saddam Hussein Al-Tikriti,NaN,...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23850,177930,EU.13474.7,(Date of UN designation: 2025-07-18),E,enterprise,NaN,NaN,NaN,Al Rowad Bank For Development & Investment,NaN,...,NaN,[EU.13474.7],[E],[enterprise],[SUDAN-EO14098 (regnumber-Registration Number) ],[regnumber],[Registration Number],[],[SD],[]
23851,177930,EU.13474.7,(Date of UN designation: 2025-07-18),E,enterprise,NaN,NaN,NaN,Khaleej Bank,NaN,...,NaN,[EU.13474.7],[E],[enterprise],[SUDAN-EO14098 (regnumber-Registration Number) ],[regnumber],[Registration Number],[],[SD],[]
23852,177930,EU.13474.7,(Date of UN designation: 2025-07-18),E,enterprise,NaN,NaN,NaN,Alkhaleej Bank Co Ltd,NaN,...,NaN,[EU.13474.7],[E],[enterprise],[SUDAN-EO14098 (regnumber-Registration Number) ],[regnumber],[Registration Number],[],[SD],[]
23853,177939,EU.13475.6,(Date of UN designation: 2025-07-18),E,enterprise,NaN,NaN,NaN,Red Rock Ltd,NaN,...,NaN,[EU.13475.6],[E],[enterprise],[Group ID: 16463 (regnumber-Registration Numbe...,[regnumber],[Registration Number],[],[00],[Date of registration: 1960s]
23854,177939,EU.13475.6,(Date of UN designation: 2025-07-18),E,enterprise,NaN,NaN,NaN,Red Rock Mining Company,NaN,...,NaN,[EU.13475.6],[E],[enterprise],[Group ID: 16463 (regnumber-Registration Numbe...,[regnumber],[Registration Number],[],[00],[Date of registration: 1960s]

In [20]:
final_df.columns

Index(['Entity_LogicalId', 'Entity_EU_ReferenceNumber', 'Entity_Remark',
       'Entity_SubjectType', 'Entity_SubjectType_ClassificationCode',
       'NameAlias_LastName', 'NameAlias_FirstName', 'NameAlias_MiddleName',
       'NameAlias_WholeName', 'NameAlias_Title', 'NameAlias_Function',
       'NameAlias_LogicalId', 'NameAlias_Remark',
       'Address_Entity_EU_ReferenceNumber', 'Address_Address_City',
       'Address_Address_Street', 'Address_Address_PoBox',
       'Address_Address_ZipCode', 'Address_Address_Region',
       'Address_Address_Place', 'Address_Address_AsAtListingTime',
       'Address_Address_ContactInfo', 'Address_Address_CountryIso2Code',
       'Address_Address_CountryDescription', 'Address_Address_Remark',
       'Citizen_Entity_EU_ReferenceNumber', 'Citizen_Entity_SubjectType',
       'Citizen_Entity_SubjectType_ClassificationCode',
       'Citizen_Citizenship_CountryIso2Code', 'Citizen_Citizenship_Remark',
       'IDN_Entity_EU_ReferenceNumber', 'IDN_Entity_SubjectType',
       'IDN_Entity_SubjectType_ClassificationCode',
       'IDN_Identification_Number', 'IDN_Identification_TypeCode',
       'IDN_Identification_TypeDescription', 'IDN_Identification_Region',
       'IDN_Identification_CountryIso2Code', 'IDN_Identification_Remark'],
      dtype='object')

In [23]:
final_df_cleaned = final_df.drop(columns=[
                                  'Entity_EU_ReferenceNumber',
                                  'NameAlias_LastName', 'NameAlias_FirstName', 'NameAlias_MiddleName',
                                  'NameAlias_LogicalId',
                                  "NameAlias_LastName",
                                  "NameAlias_FirstName",
                                  "NameAlias_MiddleName",
                                'Entity_SubjectType_ClassificationCode',
                                'NameAlias_Remark',
                                  'Address_Entity_EU_ReferenceNumber',
                                  'Address_Address_AsAtListingTime',
                                  'Address_Address_Remark',
                                  'Birth_Entity_EU_ReferenceNumber', 
                                  'Birth_BirthDate_Day', 'Birth_BirthDate_Month',
                                  'Citizen_Entity_EU_ReferenceNumber',
                                  'IDN_Entity_EU_ReferenceNumber',
                                  'IDN_Identification_TypeCode',
                                  'IDN_Identification_TypeDescription', 
                                  'IDN_Identification_Region',
                                  'IDN_Identification_CountryIso2Code', 
                                  'IDN_Identification_Remark',
                                  'Citizen_Entity_SubjectType',
                                  'Citizen_Entity_SubjectType_ClassificationCode',
                                  'Citizen_Citizenship_Remark',
                                         ])

In [24]:
final_df_cleaned.columns

Index(['Entity_LogicalId', 'Entity_Remark', 'Entity_SubjectType',
       'NameAlias_WholeName', 'NameAlias_Title', 'NameAlias_Function',
       'Address_Address_City', 'Address_Address_Street',
       'Address_Address_PoBox', 'Address_Address_ZipCode',
       'Address_Address_Region', 'Address_Address_Place',
       'Address_Address_ContactInfo', 'Address_Address_CountryIso2Code',
       'Address_Address_CountryDescription',
       'Citizen_Citizenship_CountryIso2Code', 'IDN_Entity_SubjectType',
       'IDN_Entity_SubjectType_ClassificationCode',
       'IDN_Identification_Number'],
      dtype='object')

### Combine adddress columns

In [25]:
final_df_cleaned["Address_Address_City"] = (
    final_df_cleaned[
        [
            "Address_Address_City",
            "Address_Address_Street",
            "Address_Address_PoBox",
            "Address_Address_ZipCode",
            "Address_Address_Region",
            "Address_Address_Place",
            "Address_Address_ContactInfo",
            "Address_Address_CountryIso2Code",
            "Address_Address_CountryDescription",
        ]
    ]
    .astype(str)
    .apply(lambda row: " ".join([val for val in row if val not in ["nan", "None", "", "[]"] ]), axis=1)
)

### Combine Birth Columns

In [33]:
cols_to_merge = [
    "Birth_BirthDate_Region",
    "Birth_BirthDate_Place",
    "Birth_BirthDate_City",
    "Birth_BirthDate_CountryDescription",
    "Birth_BirthDate_CountryIso2Code",
    'Birth_BirthDate_Remark',
]

In [34]:
def combine_birth_row(row):
    values = []
    for col in cols_to_merge:
        val = str(row[col]).strip()
        # skip empties
        if val in ["nan", "None", "", "[]", "UNKNOWN"]:
            continue
        # skip country code/desc if both are (00, UNKNOWN)
        if (row.get("Birth_BirthDate_CountryIso2Code") == "00" and 
            row.get("Birth_BirthDate_CountryDescription") == "UNKNOWN" and 
            col in ["Birth_BirthDate_CountryIso2Code", "Birth_BirthDate_CountryDescription"]):
            continue
        values.append(val)
    return ", ".join(values)

In [32]:
final_df_cleaned["Birth_BirthDate_Place"] = final_df_cleaned.apply(combine_birth_row, axis=1)

KeyError: 'Birth_BirthDate_Place'

In [35]:
final_df_cleaned.head(3)

,Entity_LogicalId,Entity_Remark,Entity_SubjectType,NameAlias_WholeName,NameAlias_Title,NameAlias_Function,Address_Address_City,Address_Address_Street,Address_Address_PoBox,Address_Address_ZipCode,Address_Address_Region,Address_Address_Place,Address_Address_ContactInfo,Address_Address_CountryIso2Code,Address_Address_CountryDescription,Citizen_Citizenship_CountryIso2Code,IDN_Entity_SubjectType,IDN_Entity_SubjectType_ClassificationCode,IDN_Identification_Number
0,13,(UNSC RESOLUTION 1483),P,Saddam Hussein Al-Tikriti,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[IQ],NaN,NaN,NaN
1,13,(UNSC RESOLUTION 1483),P,Abu Ali,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[IQ],NaN,NaN,NaN
2,13,(UNSC RESOLUTION 1483),P,Abou Ali,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[IQ],NaN,NaN,NaN

In [36]:
print(final_df_cleaned[["Birth_BirthDate_Place"]].head(5))

KeyError: "None of [Index(['Birth_BirthDate_Place'], dtype='object')] are in the [columns]"

### Remove Extra Address Columns

In [713]:
final_df_cleaned.columns

Index(['Entity_LogicalId', 'Entity_Remark', 'Entity_SubjectType',
       'NameAlias_WholeName', 'NameAlias_Title', 'NameAlias_Function',
       'Address_Address_City', 'Address_Address_Street',
       'Address_Address_PoBox', 'Address_Address_ZipCode',
       'Address_Address_Region', 'Address_Address_Place',
       'Address_Address_ContactInfo', 'Address_Address_CountryIso2Code',
       'Address_Address_CountryDescription', 'Birth_BirthDate_BirthDate',
       'Birth_BirthDate_Year', 'Birth_BirthDate_Region',
       'Birth_BirthDate_Place', 'Birth_BirthDate_City',
       'Birth_BirthDate_CountryIso2Code', 'Birth_BirthDate_CountryDescription',
       'Birth_BirthDate_Remark', 'Citizen_Citizenship_CountryIso2Code',
       'IDN_Entity_SubjectType', 'IDN_Entity_SubjectType_ClassificationCode',
       'IDN_Identification_Number'],
      dtype='object')

In [714]:
final_df_cleaned = final_df_cleaned.drop(columns=[
                                  'Address_Address_Street',
       'Address_Address_PoBox', 'Address_Address_ZipCode',
       'Address_Address_Region', 'Address_Address_Place',
       'Address_Address_ContactInfo', 'Address_Address_CountryIso2Code',
       'Address_Address_CountryDescription','Birth_BirthDate_Year', 'Birth_BirthDate_Region',
    'Birth_BirthDate_City', 'Birth_BirthDate_CountryIso2Code', 'Birth_BirthDate_Remark',
    'Citizen_Citizenship_CountryIso2Code','IDN_Entity_SubjectType', 'IDN_Entity_SubjectType_ClassificationCode'
                                         ])

In [715]:
final_df_cleaned.to_csv("final_output_test_v2.csv", index=False)

In [716]:
def clean_lists(x):
    if isinstance(x, list):
        # Convert list items to strings, replacing bad values with ""
        x = ["" if str(v).strip() in ["nan", "None", "", "00", "UNKNOWN",] or pd.isna(v) else str(v) for v in x]
        return ", ".join([val for val in x if val])  # join only non-empty ones
    else:
        # If single value, replace bad ones with ""
        if pd.isna(x) or str(x).strip() in ["nan", "None", "","00", "UNKNOWN",]:
            return ""
        return str(x)

In [717]:
def flatten_cell(val):
    if isinstance(val, list):
        # Join values with space or comma (your choice)
        return " ".join([str(v) for v in val if pd.notna(v) and str(v).strip() not in ["", "nan", "None"]])
    return val

In [718]:
final_df_cleaned = final_df_cleaned.map(clean_lists)

In [719]:
print(final_df_cleaned[["Birth_BirthDate_Place"]].head(5))

                        Birth_BirthDate_Place
0  ['al-Awja, near Tikrit'], ['IRAQ'], ['IQ']
1  ['al-Awja, near Tikrit'], ['IRAQ'], ['IQ']
2  ['al-Awja, near Tikrit'], ['IRAQ'], ['IQ']
3            ['Baghdad'], ['UNKNOWN'], ['00']
4            ['Baghdad'], ['UNKNOWN'], ['00']

In [720]:
final_df_cleaned["Address_Address_City"] = final_df_cleaned["Address_Address_City"].apply(flatten_cell)
final_df_cleaned["Birth_BirthDate_Place"] = final_df_cleaned["Birth_BirthDate_Place"].apply(flatten_cell)

In [721]:
print(final_df_cleaned[["Birth_BirthDate_Place"]].head(5))

                        Birth_BirthDate_Place
0  ['al-Awja, near Tikrit'], ['IRAQ'], ['IQ']
1  ['al-Awja, near Tikrit'], ['IRAQ'], ['IQ']
2  ['al-Awja, near Tikrit'], ['IRAQ'], ['IQ']
3            ['Baghdad'], ['UNKNOWN'], ['00']
4            ['Baghdad'], ['UNKNOWN'], ['00']

In [722]:
print(final_df_cleaned[["Birth_BirthDate_Place"]].head(5))

                        Birth_BirthDate_Place
0  ['al-Awja, near Tikrit'], ['IRAQ'], ['IQ']
1  ['al-Awja, near Tikrit'], ['IRAQ'], ['IQ']
2  ['al-Awja, near Tikrit'], ['IRAQ'], ['IQ']
3            ['Baghdad'], ['UNKNOWN'], ['00']
4            ['Baghdad'], ['UNKNOWN'], ['00']

### Change the column names

In [723]:
final_df_cleaned.columns

Index(['Entity_LogicalId', 'Entity_Remark', 'Entity_SubjectType',
       'NameAlias_WholeName', 'NameAlias_Title', 'NameAlias_Function',
       'Address_Address_City', 'Birth_BirthDate_BirthDate',
       'Birth_BirthDate_Place', 'Birth_BirthDate_CountryDescription',
       'IDN_Identification_Number'],
      dtype='object')

In [724]:
final_df_cleaned = final_df_cleaned.rename(columns={
    "Entity_LogicalId": "OfficialID",
    "Entity_SubjectType": "Type",
    "NameAlias_WholeName": "Name",
    "NameAlias_Title": "Title",
    "NameAlias_Function": "Designation",
    "Address_Address_City": "Address",
    "Birth_BirthDate_BirthDate": "BirthDate",
    "Birth_BirthDate_Place": "POB",
    "Birth_BirthDate_CountryDescription": "CitizenOf",
    "IDN_Identification_Number": "IdentityDetails",
     "Entity_Remark": "Remarks",
})

### Add a new Column to the dataframe

In [725]:
final_df_cleaned["Source"] = "EU"

In [726]:
final_df_cleaned.to_csv("final_output_test_v3.csv", index=False)